---
title: "My Server"
subtitle: "Welcome To"
#logo: "logo.png"
icon: "fas fa-server"

header: true
footer: 'My Awesome Home Server' # Set false if you want to hide it.

stylesheet:
  - "assets/custom.css"

search: true

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#0000001a"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    background-color: "#6d0a814d"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#21183A45"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#d9d9d9"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/"
    target: "_blank" # optional html a tag target attribute
  - name: "Docker Hub"
    icon: "fab fa-docker"
    url: "https://hub.docker.com/"
    target: "_blank"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).

services:
  - name: "Category 1"
    icon: "fas fa-cogs"
    items:
      - name: "GitHub"
        logo: "assets/tools/github.png"
        subtitle: "The Open Source Community"
        url: "https://github.com"
        target: "_blank" # optional html a tag target attribute
  - name: "Category 2"
    icon: "fas fa-network-wired"
    items:
      - name: "Reddit"
        logo: "assets/tools/reddit.png"
        subtitle: "Dive into your interests and passions"
        url: "https://reddit.com"
        target: "_blank"